### ISSUE TITLE
Mesh for  ReSynth dataset

### ISSUE THREAD

**Issue by ray8828** [qianlim/POP#10]
Hi, thanks for sharing this great work, I'm wondering how can i get the original meshes from which the scan point cloud is generated? Are they included somewhere in the dataset we downloaded or they are not provided? Thanks!!

**Comment by qianlim** [comment]
Hi, unfortunately the original meshes were accidentally deleted so we can't recover them either :( As a compromise you can try to run Poisson reconstruction on the dense point clouds, it works sufficiently well.

**Comment by ray8828** [comment]
Thanks, got it!
