### ISSUE TITLE
Point rendering with surfels

### ISSUE THREAD

**Issue by zhaofang0627** [qianlim/POP#11]
Hi, 

In Fig 4. of the paper, you mentioned that the point clouds are rendered with surfels. Could you kindly share the code for the point rendering with surfels?

Thanks!

**Comment by qianlim** [comment]
Hi, we just used Open3D for rendering; see the render/ folder in this repo.

**Comment by zhaofang0627** [comment]
Thanks for your quick reply! It's very helpful.
