### ISSUE TITLE
double self.upconv3

### ISSUE THREAD

**Issue by caiyongqi** [qianlim/POP#12]
Is this a bug? Double `self.upconv3`.
https://github.com/qianlim/POP/blob/a05404dd44173809abfee4e2ebef57bbc524cfde/lib/modules.py#L413

**Comment by qianlim** [comment]
You are right! Let me first check how the performance changes after fixing this.

**Comment by caiyongqi** [comment]
> You are right! Let me first check how the performance changes after fixing this.

Thank you! Now I close this issue.

**Comment by qianlim** [comment]
> 
It's fixed now. In my test fixing this bug doesn't influence the performance.
