### ISSUE TITLE
chamfer distance

### ISSUE THREAD

**Issue by caiyongqi** [qianlim/POP#13]
Hi. You don't seem to be using the chamfer distance directly as the loss, would the performance be better?
https://github.com/qianlim/POP/blob/a05404dd44173809abfee4e2ebef57bbc524cfde/lib/train.py#L87
https://github.com/qianlim/POP/blob/a05404dd44173809abfee4e2ebef57bbc524cfde/lib/train.py#L98

**Comment by qianlim** [comment]
I'd say the performance difference is very small when the points are dense. It's computed this way due to some historical reasons. Just using the plain chamfer distance should also be fine.

**Comment by caiyongqi** [comment]
> I'd say the performance difference is very small when the points are dense. It's computed this way due to some historical reasons. Just using the plain chamfer distance should also be fine.

Thank you! Now I close this issue.
