### ISSUE TITLE
The "geom_featmap" seems to be reset during training

### ISSUE THREAD

**Issue by wenbin-lin** [qianlim/POP#15]
For evaluation during training, the value of the "geom_featmap" seems to be reset to the most recently saved value.
https://github.com/qianlim/POP/blob/a05404dd44173809abfee4e2ebef57bbc524cfde/main.py#L193-L195
The "geom_featmap" is saved every 50 epochs, while the default value of the "args.val_every" is set to 20. 
Therefore, the value of the "geom_featmap" will be reset several times. For example, at the 20th or 40th epoch, the "geom_featmap" will be set to the initial value of the 0th epoch.
Is this a bug?

**Comment by qianlim** [comment]
You are right! It's fixed now. I just verified fixing it doesn't worsen the performance.

**Comment by wenbin-lin** [comment]
Thank you.
