### ISSUE TITLE
python main.py --config configs/config_demo.yaml --mode test

### ISSUE THREAD

**Issue by QUMINGZHEMENAN** [qianlim/POP#17]
(POP) siduo@siduo-NK50S5-SZ:~/下载/POP-main$ python main.py --config configs/config_demo.yaml --mode test

------------------------Loading checkpoint POP_pretrained_ReSynthdata_12outfits_epoch00400_model.pt

------------------------Test model with checkpoint at epoch 400

------------------------Eval on test data, seen outfits, unseen poses...
Loading test data...
Loading rp_alexandra_posed_006, 0 examples..
0it [00:00, ?it/s]
Data loaded, in total 0 test examples.

Evaluating...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "main.py", line 354, in <module>
    main()
  File "main.py", line 256, in main
    test_stats = test_seen_clo(
  File "/home/siduo/下载/POP-main/lib/infer.py", line 316, in test_seen_clo
    test_m2s /= n_test_samples
ZeroDivisionError: division by zero

**Comment by QUMINGZHEMENAN** [comment]
@qianlim Excuse me big guy this problem, is how to return a responsibility how to solve？

**Comment by qianlim** [comment]
It seems no data was loaded. Please take a look at README and try downloading some data and place them in the correct path.
