### ISSUE TITLE
Data preprocess

### ISSUE THREAD

**Issue by zhaofang0627** [qianlim/POP#5]
Hi, 

Thanks for sharing your great work! I notice that the scale and translation of "scan_pc" and "body_verts" in the provided packed data are different from meshes in the original CAPE dataset. What is the scale and translation parameters you used to normalize the meshes? 

Thanks!

**Comment by qianlim** [comment]
Hi, the bodies are pelvis-aligned according to the fitted minimal SMPL bodies in the original CAPE data.

To do so, we use the per-subject v_template and the pose parameter of each frame in the original CAPE data, feed them to SMPL model, get the pelvis joint location (0th joint), and subtract that from the scan_pc and body_verts.
I'm not sure about the scale though, are you sure they are also different?

**Comment by zhaofang0627** [comment]
Thank you for your reply! I translate the mesh in the original CAPE data by subtract the difference between its and scan_pc's centers. The result is like the following pics. The scale is the same but it seems that the rotation angle is a little different. 
<img width="347" alt="20211109-000407@2x" src="https://user-images.githubusercontent.com/11569189/140776382-cedf2a6a-046d-4eff-8430-ec5b5f1808bc.png">
<img width="342" alt="20211109-000340@2x" src="https://user-images.githubusercontent.com/11569189/140776400-11aef6c0-eca0-4304-9291-8d14d7cfa53d.png">

**Comment by qianlim** [comment]
Oh right! we set the global orientation (first 3 dims of the SMPL pose parameters) to be zero too.

**Comment by zhaofang0627** [comment]
Thanks! They are now aligned.
